import { Inter } from "next/font/google";
import "./globals.css";
import Sidebare from "@/components/sideCompo/Sidebare";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:grid" style={{ gridTemplateColumns: "60px 1fr" }}>
          <Sidebare />
          {children}
        </div>
      </body>
    </html>
  );
}
